# External Secrets for HRMS Application
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-database-secrets
  namespace: hrms-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-database-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: hrms/staging/database
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: hrms/staging/database
      property: password
  - secretKey: DB_HOST
    remoteRef:
      key: hrms/staging/database
      property: host
  - secretKey: DB_PORT
    remoteRef:
      key: hrms/staging/database
      property: port

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-redis-secrets
  namespace: hrms-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-redis-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_HOST
    remoteRef:
      key: hrms/staging/redis
      property: host
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: hrms/staging/redis
      property: password
  - secretKey: REDIS_PORT
    remoteRef:
      key: hrms/staging/redis
      property: port

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-jwt-secrets
  namespace: hrms-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-jwt-secrets
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: hrms/staging/jwt
      property: secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: hrms/staging/jwt
      property: refresh_secret
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: hrms/staging/jwt
      property: encryption_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-email-secrets
  namespace: hrms-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-email-secrets
    creationPolicy: Owner
  data:
  - secretKey: SMTP_USER
    remoteRef:
      key: hrms/staging/email
      property: smtp_user
  - secretKey: SMTP_PASS
    remoteRef:
      key: hrms/staging/email
      property: smtp_password
  - secretKey: EMAIL_FROM
    remoteRef:
      key: hrms/staging/email
      property: from_address

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-aws-secrets
  namespace: hrms-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-aws-secrets
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: hrms/staging/aws
      property: access_key_id
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: hrms/staging/aws
      property: secret_access_key
  - secretKey: AWS_S3_BUCKET
    remoteRef:
      key: hrms/staging/aws
      property: s3_bucket
  - secretKey: AWS_REGION
    remoteRef:
      key: hrms/staging/aws
      property: region

---
# Production External Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-database-secrets
  namespace: hrms-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-database-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: hrms/production/database
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: hrms/production/database
      property: password
  - secretKey: DB_HOST
    remoteRef:
      key: hrms/production/database
      property: host
  - secretKey: DB_PORT
    remoteRef:
      key: hrms/production/database
      property: port

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-redis-secrets
  namespace: hrms-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-redis-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_HOST
    remoteRef:
      key: hrms/production/redis
      property: host
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: hrms/production/redis
      property: password
  - secretKey: REDIS_PORT
    remoteRef:
      key: hrms/production/redis
      property: port

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-jwt-secrets
  namespace: hrms-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-jwt-secrets
    creationPolicy: Owner
  data:
  - secretKey: JWT_SECRET
    remoteRef:
      key: hrms/production/jwt
      property: secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: hrms/production/jwt
      property: refresh_secret
  - secretKey: ENCRYPTION_KEY
    remoteRef:
      key: hrms/production/jwt
      property: encryption_key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-email-secrets
  namespace: hrms-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-email-secrets
    creationPolicy: Owner
  data:
  - secretKey: SMTP_USER
    remoteRef:
      key: hrms/production/email
      property: smtp_user
  - secretKey: SMTP_PASS
    remoteRef:
      key: hrms/production/email
      property: smtp_password
  - secretKey: EMAIL_FROM
    remoteRef:
      key: hrms/production/email
      property: from_address

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-aws-secrets
  namespace: hrms-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: hrms-aws-secrets
    creationPolicy: Owner
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: hrms/production/aws
      property: access_key_id
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: hrms/production/aws
      property: secret_access_key
  - secretKey: AWS_S3_BUCKET
    remoteRef:
      key: hrms/production/aws
      property: s3_bucket
  - secretKey: AWS_REGION
    remoteRef:
      key: hrms/production/aws
      property: region
